### ISSUE TITLE
Retux Has Malware !

### ISSUE THREAD

**Issue by deonsebastiandk** [retux-game/retux#3] opened 2021-05-11 08:01 UTC
Dear Retux team please remove malware from the retux-zip file . it has many types of viruses . It was detected by many antiviruses . please remove to viruses from the Retux-win64 zip file as soon as possible

**Comment by onpon4** [comment] 2021-05-11 14:02
I just tried scanning both the zip and the files in the zip with ClamAV and it found no possible threats. I also know that the binary is essentially just Python bundled with the ReTux scripts with, something I did with PyInstaller on Wine. Could you please be more specific with your claim that it "has many types of viruses" "detected by many antiviruses"?

🕵️

**Comment by onpon4** [comment] 2021-05-11 22:16
Ok. I've taken a look. Here's a summary of my findings:

* "Gen:Variant.Bulz.460117" is a generic diagnostic caution based on multiple programs being bundled together. I can only assume that the antivirus programs stating this are doing so because ReTux is, technically speaking, the Python interpreter bundled with Python scripts. But as I don't have any knowledge of how these diagnostics work, I can't say for sure. In any case, this is a false positive because the bundling isn't malicious, it's merely necessary to enable ReTux to run on computers that don't have Python installed.
* "Malicious_Behavior.SB" is some kind of classification of behavior an antivirus thinks is suspicious. This seems to be a false positive.
* "Malware (ai Score=86)" is something I can't fully assess, but it seems to be another false-positive general diagnostic so far as I can tell, and it is only reported by MAX.
* Under McAfee, "Artemis" is a generic mark of "suspicion" for files that it can't positively identify as a threat. This too seems to be a false positive.
* I note that findings by antiviruses is very inconsistent even though the same file is always being checked. For instance, https://www.virustotal.com/gui/url/7b3732f4c5451cbdb05478abd68aed9d4db223d7b9246349651837083dd0efdc/detection shows no infections at all at this time, and this is for the direct link to the file on GitHub (which I can confirm has the same hash as the one you linked to, which is also the one my girlfriend linked me to this morning).

Given all of this, I think I can confidently say that the few reports of threats detected are false positives, and so I am closing this issue as invalid. As I said, the ReTux Windows binary is only a bundle of Python and ReTux put together by PyInstaller. It is not malicious, and it was not produced on a malware-infected system. If your antivirus software is one of the few which have the false positive, I suggest contacting the developers of the software so they can correct their database. Alternatively, if you still don't trust the binary, you are welcome to download Python and the required libraries yourself so you can run the source code directly.

🕵️

**Closed by onpon4** 2021-05-11 22:16 UTC
Labels: invalid
